export enum CharsActionTypes {
    FETCH_CHARS_REQUEST = 'FETCH_CHARS_REQUEST',
    FETCH_CHARS_SUCCESS = 'FETCH_CHARS_SUCCESS',
    FETCH_CHARS_FAILURE = 'FETCH_CHARS_FAILURE',
    DELETE_CHAR = 'DELETE_CHAR',
    LIKE_CHAR = 'LIKE_CHAR',
    FILTER_LIKED_CHARS = 'FILTER_LIKED_CHARS'
}